CREATE TABLE programs (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(150) NOT NULL,
                          presenter VARCHAR(150) NOT NULL
);
