CREATE TABLE schedule_entries (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  program_id BIGINT NOT NULL,
                                  day_of_week VARCHAR(10) NOT NULL,
                                  start_time TIME NOT NULL,

                                  CONSTRAINT fk_schedule_entries_program
                                      FOREIGN KEY (program_id)
                                          REFERENCES programs(id)
);
