spring.application.name=radio-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/online_radio}
spring.datasource.username=${DB_USERNAME:radio_app}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.open-in-view=false
